import type { Order, FilterOption, ClientOption } from "./types"

export const orders: Order[] = [
  {
    id: "ord001",
    time: "08:14:31",
    client: "AAA001",
    ticker: "RELIANCE",
    tickerAudio: true,
    side: "Buy",
    product: "CNC",
    qty: "50/100",
    price: "250.50",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord002",
    time: "08:14:31",
    client: "AAA003",
    ticker: "MRF",
    side: "Buy",
    product: "NRML",
    qty: "10/20",
    price: "2,700.00",
    status: "Partial",
    type: "Market",
  },
  {
    id: "ord003",
    time: "08:14:31",
    client: "AAA002",
    ticker: "ASIANPAINT",
    tickerAudio: true,
    side: "Buy",
    product: "NRML",
    qty: "10/30",
    price: "1,500.60",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord004",
    time: "08:14:31",
    client: "AAA002",
    ticker: "TATAINVEST",
    side: "Sell",
    product: "INTRADAY",
    qty: "10/10",
    price: "2,300.10",
    status: "Filled",
    type: "Market",
  },
  {
    id: "ord005",
    time: "08:15:22",
    client: "AAA001",
    ticker: "HDFCBANK",
    side: "Buy",
    product: "CNC",
    qty: "25/50",
    price: "1,650.75",
    status: "Partial",
    type: "Limit",
  },
  {
    id: "ord006",
    time: "08:16:05",
    client: "AAA004",
    ticker: "TCS",
    tickerAudio: true,
    side: "Buy",
    product: "NRML",
    qty: "5/15",
    price: "3,450.25",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord007",
    time: "08:17:12",
    client: "AAA002",
    ticker: "INFY",
    side: "Sell",
    product: "INTRADAY",
    qty: "20/20",
    price: "1,820.40",
    status: "Filled",
    type: "Market",
  },
  {
    id: "ord008",
    time: "08:18:30",
    client: "AAA003",
    ticker: "WIPRO",
    side: "Buy",
    product: "CNC",
    qty: "30/60",
    price: "420.15",
    status: "Partial",
    type: "Limit",
  },
  {
    id: "ord009",
    time: "08:19:45",
    client: "AAA001",
    ticker: "ICICIBANK",
    tickerAudio: true,
    side: "Buy",
    product: "NRML",
    qty: "15/30",
    price: "950.80",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord010",
    time: "08:20:10",
    client: "AAA004",
    ticker: "SBIN",
    side: "Sell",
    product: "INTRADAY",
    qty: "40/40",
    price: "625.30",
    status: "Filled",
    type: "Market",
  },
  {
    id: "ord011",
    time: "08:21:22",
    client: "AAA002",
    ticker: "BAJFINANCE",
    side: "Buy",
    product: "CNC",
    qty: "8/16",
    price: "7,250.60",
    status: "Partial",
    type: "Limit",
  },
  {
    id: "ord012",
    time: "08:22:15",
    client: "AAA003",
    ticker: "AXISBANK",
    tickerAudio: true,
    side: "Buy",
    product: "NRML",
    qty: "12/24",
    price: "875.45",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord013",
    time: "08:23:05",
    client: "AAA001",
    ticker: "KOTAKBANK",
    side: "Sell",
    product: "INTRADAY",
    qty: "18/18",
    price: "1,920.75",
    status: "Filled",
    type: "Market",
  },
  {
    id: "ord014",
    time: "08:24:30",
    client: "AAA004",
    ticker: "MARUTI",
    side: "Buy",
    product: "CNC",
    qty: "3/6",
    price: "10,450.20",
    status: "Partial",
    type: "Limit",
  },
  {
    id: "ord015",
    time: "08:25:15",
    client: "AAA002",
    ticker: "TATAMOTORS",
    tickerAudio: true,
    side: "Buy",
    product: "NRML",
    qty: "35/70",
    price: "750.90",
    status: "Pending",
    type: "Limit",
  },
  {
    id: "ord016",
    time: "08:26:40",
    client: "AAA003",
    ticker: "HINDUNILVR",
    side: "Sell",
    product: "INTRADAY",
    qty: "10/10",
    price: "2,580.35",
    status: "Filled",
    type: "Market",
  },
]

export const clientOptions: ClientOption[] = [
  { id: "client1", name: "AAA001" },
  { id: "client2", name: "AAA002" },
  { id: "client3", name: "AAA003" },
  { id: "client4", name: "AAA004" },
]

export const filterOptions: FilterOption[] = [
  { id: "filter1", label: "Lalit", value: "Lalit" },
  { id: "filter2", label: "Rahul", value: "Rahul" },
  { id: "filter3", label: "Priya", value: "Priya" },
  { id: "filter4", label: "Vikram", value: "Vikram" },
]

export const tickerOptions: FilterOption[] = [
  { id: "ticker1", label: "RELIANCE", value: "RELIANCE" },
  { id: "ticker2", label: "ASIANPAINT", value: "ASIANPAINT" },
  { id: "ticker3", label: "TATAINVEST", value: "TATAINVEST" },
  { id: "ticker4", label: "HDFCBANK", value: "HDFCBANK" },
  { id: "ticker5", label: "TCS", value: "TCS" },
  { id: "ticker6", label: "INFY", value: "INFY" },
]

export const productOptions: FilterOption[] = [
  { id: "product1", label: "CNC", value: "CNC" },
  { id: "product2", label: "NRML", value: "NRML" },
  { id: "product3", label: "INTRADAY", value: "INTRADAY" },
]

export const sideOptions: FilterOption[] = [
  { id: "side1", label: "Buy", value: "Buy" },
  { id: "side2", label: "Sell", value: "Sell" },
]

export const statusOptions: FilterOption[] = [
  { id: "status1", label: "Pending", value: "Pending" },
  { id: "status2", label: "Partial", value: "Partial" },
  { id: "status3", label: "Filled", value: "Filled" },
]
